#! /usr/bin/env node
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/cli.ts
var import_commander = require("commander");

// package.json
var package_default = {
  name: "set-defaults",
  version: "0.0.5",
  description: "copy default files to their actual file name",
  publishConfig: {
    access: "public"
  },
  type: "module",
  main: "dist/index.cjs",
  module: "dist/index.js",
  types: "dist/index.d.ts",
  bin: {
    "set-defaults": "dist/cli.cjs"
  },
  devDependencies: {
    "@types/node": "^18.15.5",
    rimraf: "^4.4.1",
    tsup: "^6.7.0",
    typescript: "^4.9.5"
  },
  dependencies: {
    commander: "^10.0.0"
  },
  scripts: {
    build: "rimraf dist && tsup --entry src/index.ts --entry src/cli.ts --dts --format esm,cjs"
  }
};

// src/utils/files.ts
var import_node_fs = __toESM(require("fs"), 1);
var import_node_path = __toESM(require("path"), 1);
function copyUnlessExists(from, to) {
  if (!import_node_fs.default.existsSync(to)) {
    if (import_node_fs.default.existsSync(from)) {
      import_node_fs.default.copyFileSync(from, to);
      return true;
    }
  }
  return false;
}
function copyFromDefault(p) {
  return copyUnlessExists(`${p}.default`, p);
}
function copyFromAllDefault(folderOrFile) {
  if (import_node_fs.default.existsSync(folderOrFile)) {
    if (import_node_fs.default.statSync(folderOrFile).isDirectory()) {
      const files = import_node_fs.default.readdirSync(folderOrFile).filter((v) => v.endsWith(".default")).map((v) => import_node_path.default.join(folderOrFile, v.slice(0, v.length - 8)));
      return files.map(copyFromDefault).reduce((prev, curr) => prev || curr, false);
    } else {
      if (!folderOrFile.endsWith(".default")) {
        return false;
      }
      return copyFromDefault(folderOrFile.slice(0, folderOrFile.length - 8));
    }
  } else {
    return false;
  }
}

// src/index.ts
function copyDefaults(config) {
  return __async(this, null, function* () {
    const resolvedConfig = __spreadValues({ foldersOrFiles: ["."] }, config);
    let anyChanges = false;
    for (const folder of resolvedConfig.foldersOrFiles) {
      anyChanges = copyFromAllDefault(folder) || anyChanges;
    }
  });
}

// src/cli.ts
var name = package_default.name;
var program = new import_commander.Command();
program.name(name).version(package_default.version).usage(`[dirs|files...]`).argument(`[dirs|files...]`).description("copy default files to their respective filename").action((foldersOrFiles) => {
  copyDefaults({ foldersOrFiles: foldersOrFiles || ["."] });
});
program.parse();
//# sourceMappingURL=cli.cjs.map